version: '3.6'
services:
  iris:
    environment:
      - SAMPLE_TOKEN=${SAMPLE_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
    hostname: xml-sample
    container_name: iris-xml-sample
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972
      - 52796:52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev/
